export const STORAGE_WORD_INFO = 'STORAGE_WORD_INFO';
export const STORAGE_GUSSED = 'STORAGE_GUSSED';
export const STORAGE_INVALID_GUSSES = 'STORAGE_INVALID_GUSSES';
export const STORAGE_LIVES = 'STORAGE_LIVES';
export const STORAGE_PLACEHOLDER = 'STORAGE_PLACEHOLDER';
export const STORAGE_LETTERS = 'STORAGE_LETTERS';
export const STORAGE_KEYBOARD_DRAWN = 'STORAGE_KEYBOARD_DRAWN';